
/*
 *  This file was generated by the SOM Compiler.
 *  Generated using: 
 *      SOM Emitter emitxtm.dll: 2.33
 */

#define VARIABLE_MACROS
#define som_EmbeddedFramesIterator_Class_Source
#include "som_FrameIterator.xih"

#include	"SampleCollections.h"

#ifndef SOM_SophistSolutions_som_LedPart_xh
#include "som_LedPart.xh"
#endif
#include "Except.h"

#ifndef _ODUTILS_
#include "ODUtils.h"
#endif

SOM_Scope void  SOMLINK som_EmbeddedFramesIteratorsomInit(som_EmbeddedFramesIterator *somSelf)
{
    som_EmbeddedFramesIteratorData *somThis = som_EmbeddedFramesIteratorGetData(somSelf);
    som_EmbeddedFramesIteratorMethodDebug("som_EmbeddedFramesIterator","som_EmbeddedFramesIteratorsomInit");

    som_EmbeddedFramesIterator_parents_somInit(somSelf);
    
	_fOrderedCollectionIterator = kODNULL;
}

SOM_Scope void  SOMLINK som_EmbeddedFramesIteratorInitEmbeddedFramesIterator(som_EmbeddedFramesIterator *somSelf, Environment *ev,
		ODPart* part)
{
    som_EmbeddedFramesIteratorData *somThis = som_EmbeddedFramesIteratorGetData(somSelf);
    som_EmbeddedFramesIteratorMethodDebug("som_EmbeddedFramesIterator","som_EmbeddedFramesIteratorInitEmbeddedFramesIterator");

    som_EmbeddedFramesIterator_parent_ODEmbeddedFramesIterator_InitEmbeddedFramesIterator(somSelf,ev,part);

	SOM_TRY
		_fOrderedCollectionIterator = new COrdListIterator(((SophistSolutions_som_LedPart*)part)->GetEmbeddedFrames(ev));
	SOM_CATCH_ALL
		ODDeleteObject(_fOrderedCollectionIterator);
		_fOrderedCollectionIterator = kODNULL;
	SOM_ENDTRY
}

SOM_Scope void  SOMLINK som_EmbeddedFramesIteratorsomUninit(som_EmbeddedFramesIterator *somSelf)
{
    som_EmbeddedFramesIteratorData *somThis = som_EmbeddedFramesIteratorGetData(somSelf);
    som_EmbeddedFramesIteratorMethodDebug("som_EmbeddedFramesIterator","som_EmbeddedFramesIteratorsomUninit");

	ODDeleteObject(_fOrderedCollectionIterator);
  
    som_EmbeddedFramesIterator_parent_ODEmbeddedFramesIterator_somUninit(somSelf);
}

SOM_Scope ODFrame*  SOMLINK som_EmbeddedFramesIteratorFirst(som_EmbeddedFramesIterator *somSelf, Environment *ev)
{
    som_EmbeddedFramesIteratorData *somThis = som_EmbeddedFramesIteratorGetData(somSelf);
    som_EmbeddedFramesIteratorMethodDebug("som_EmbeddedFramesIterator","som_EmbeddedFramesIteratorFirst");

	return (ODFrame*) _fOrderedCollectionIterator->First();
}

SOM_Scope ODFrame*  SOMLINK som_EmbeddedFramesIteratorNext(som_EmbeddedFramesIterator *somSelf, Environment *ev)
{
    som_EmbeddedFramesIteratorData *somThis = som_EmbeddedFramesIteratorGetData(somSelf);
    som_EmbeddedFramesIteratorMethodDebug("som_EmbeddedFramesIterator","som_EmbeddedFramesIteratorNext");

	return (ODFrame*) _fOrderedCollectionIterator->Next();
}

SOM_Scope ODBoolean  SOMLINK som_EmbeddedFramesIteratorIsNotComplete(som_EmbeddedFramesIterator *somSelf, Environment *ev)
{
    som_EmbeddedFramesIteratorData *somThis = som_EmbeddedFramesIteratorGetData(somSelf);
    som_EmbeddedFramesIteratorMethodDebug("som_EmbeddedFramesIterator","som_EmbeddedFramesIteratorIsNotComplete");

	return _fOrderedCollectionIterator->IsNotComplete();
}

SOM_Scope void  SOMLINK som_EmbeddedFramesIteratorPartRemoved(som_EmbeddedFramesIterator *somSelf, Environment *ev)
{
    som_EmbeddedFramesIteratorData *somThis = som_EmbeddedFramesIteratorGetData(somSelf);
    som_EmbeddedFramesIteratorMethodDebug("som_EmbeddedFramesIterator","som_EmbeddedFramesIteratorPartRemoved");

	ODDeleteObject(_fOrderedCollectionIterator);
}

SOM_Scope ODBoolean  SOMLINK som_EmbeddedFramesIteratorIsValid(som_EmbeddedFramesIterator *somSelf, Environment *ev)
{
    som_EmbeddedFramesIteratorData *somThis = som_EmbeddedFramesIteratorGetData(somSelf);
    som_EmbeddedFramesIteratorMethodDebug("som_EmbeddedFramesIterator","som_EmbeddedFramesIteratorIsValid");

	return ( _fOrderedCollectionIterator != kODNULL );
}

SOM_Scope void  SOMLINK som_EmbeddedFramesIteratorCheckValid(som_EmbeddedFramesIterator *somSelf, Environment *ev)
{
    som_EmbeddedFramesIteratorData *somThis = som_EmbeddedFramesIteratorGetData(somSelf);
    som_EmbeddedFramesIteratorMethodDebug("som_EmbeddedFramesIterator","som_EmbeddedFramesIteratorCheckValid");

	if ( _fOrderedCollectionIterator == kODNULL )
		ODSetSOMException(ev, kODErrUndefined);  // Should be kODErrInvalidBase
}
