/*
 * Copyright(c) Sophist Solutions, Inc. 1990-2016.  All rights reserved
 */
#ifndef	_Stroika_Foundation_Configuration_StroikaCurrentConfiguration_h_
#define	_Stroika_Foundation_Configuration_StroikaCurrentConfiguration_h_	1

//WARNING: THIS FILE WAS AUTOGENERATED WITH ApplyConfiguration.pl
//WARNING: THIS FILE WAS AUTOGENERATED WITH ApplyConfiguration.pl
//WARNING: THIS FILE WAS AUTOGENERATED WITH ApplyConfiguration.pl
//WARNING: THIS FILE WAS AUTOGENERATED WITH ApplyConfiguration.pl
//WARNING: THIS FILE WAS AUTOGENERATED WITH ApplyConfiguration.pl
//WARNING: THIS FILE WAS AUTOGENERATED WITH ApplyConfiguration.pl
//WARNING: THIS FILE WAS AUTOGENERATED WITH ApplyConfiguration.pl


//Defaults overrides:
//--enable-assertions or --disable-assertions to force a particular value. --default-assertions to depend on NDEBUG
// set
#define	qDebug 1


//--LibCurl {build-only|use|use-system|no}
#define	qHasFeature_LibCurl 0

//--OpenSSL {build-only|use|use-system|no}
#define	qHasFeature_OpenSSL 1

//--WinHTTP {use-system|no}
#define	qHasFeature_WinHTTP 1

//--ATLMFC {use-system|no}
#define	qHasFeature_ATLMFC 1

//--Xerces {build-only|use|use-system|no}
#define	qHasFeature_Xerces	1

//--ZLib {build-only|use|use-system|no}
#define	qHasFeature_ZLib	1

//--LZMA {build-only|use|use-system|no}
#define	qHasFeature_LZMA	1




// --trace2file enable or  --trace2file disable
// set
#define	qTraceToFile 0


//Configure Command Line Arguments (-c-define)


#endif	/*_Stroika_Foundation_Configuration_StroikaCurrentConfiguration_h_*/
