FROM sophist-solutions-inc/stroika-buildvm-ubuntu1804-small

RUN apt-get update && apt-get install -y \
	g++-7 \
	g++-8 \
	clang++-6 \
	libasan4 \
	libasan5 \
	libc++-dev \
	libubsan0 \
	libubsan1 \
	p7zip-full \
	git \
	pkg-config \
	automake \
	wget \
	unzip \
	locales \
	cmake \
	libtool-bin
