all:	Library/Stroika.a	\
		Applications

Library/Stroika.a:	PHONY
	(cd Library; cmake Stroika.a)
	(cd Applications; cmake)

Applications: PHONY
	(cd Applications; cmake)

clean: PHONY
	(cd Library; cmake clean)
	(cd Applications; cmake clean)

clobber: PHONY
	(cd Library; cmake clobber)
	(cd Applications; cmake clobber)

PHONY:
	

# For gnuemacs:
# Local Variables: ***
# mode:Text ***
# tab-width:4 ***
# End: ***
