#!/bin/bash
echo "ScriptsLib/ApplyConfiguration: this location is deprecated, use Build/ScriptsLib/ApplyConfiguration instead" >&2
exec "$(dirname "${BASH_SOURCE[0]}")/../Build/ScriptsLib/ApplyConfiguration" "$@"
