#!/bin/bash
echo "ScriptsLib/ApplyConfiguration: this location is deprecated, use Build/Scripts/ApplyConfiguration instead" >&2
exec "$(dirname "${BASH_SOURCE[0]}")/../Build/Scripts/ApplyConfiguration" "$@"
