#!/bin/bash
echo "ScriptsLib/CheckForLibrary: this location is deprecated, use Build/ScriptsLib/CheckForLibrary instead" >&2
exec "$(dirname "${BASH_SOURCE[0]}")/../Build/ScriptsLib/CheckForLibrary" "$@"
