#!/bin/bash
echo "ScriptsLib/CheckValidConfiguration: this location is deprecated, use Build/Scripts/CheckValidConfiguration instead" >&2
exec "$(dirname "${BASH_SOURCE[0]}")/../Build/Scripts/CheckValidConfiguration" "$@"
