#!/bin/bash
echo "ScriptsLib/CheckValidConfiguration: this location is deprecated, use Build/ScriptsLib/CheckValidConfiguration instead" >&2
exec "$(dirname "${BASH_SOURCE[0]}")/../Build/ScriptsLib/CheckValidConfiguration" "$@"
