#!/bin/bash
echo "ScriptsLib/CheckFileExists: this location is deprecated, use Build/ScriptsLib/CheckFileExists instead" >&2
exec "$(dirname "${BASH_SOURCE[0]}")/../Build/ScriptsLib/CheckFileExists" "$@"
