#!/bin/sh

openssl genrsa -out private_key.pem 2048
openssl req -new -key private_key.pem -out certificate_request.csr
openssl x509 -req -days 365 -signkey private_key.pem -in certificate_request.csr -out public_certificate.crt
