#!/bin/bash
echo "ScriptsLib/CreateSelfSignedCert: this location is deprecated, use Build/Scripts/CreateSelfSignedCert instead" >&2
exec "$(dirname "${BASH_SOURCE[0]}")/../Build/Scripts/CreateSelfSignedCert" "$@"
