#!/bin/bash
echo "ScriptsLib/DetectedHostOS: this location is deprecated, use Build/ScriptsLib/DetectedHostOS instead" >&2
exec "$(dirname "${BASH_SOURCE[0]}")/../Build/ScriptsLib/DetectedHostOS" "$@"
