#!/bin/sh
VER=`dos2unix < STROIKA_VERSION | xargs echo -n`
echo "STROIKA_VERSION=$VER"
echo "Checking out v2.1-Release"
git checkout v2.1-Release
echo "Pull..."
git pull --rebase
echo "Merge in v2.1-Dev..."
git merge v2.1-Dev
echo "OK to commit/push?: CTRLC to stop or RETURN to continue"
read isOK
#git commit
git push
git tag v$VER
git push origin v$VER
git checkout v2.1-Dev
