#!/bin/bash
echo "ScriptsLib/ExtractVersionInformation: this location is deprecated, use Build/ScriptsLib/ExtractVersionInformation instead" >&2
exec "$(dirname "${BASH_SOURCE[0]}")/../Build/ScriptsLib/ExtractVersionInformation" "$@"
