#!/bin/bash
echo "ScriptsLib/GetConfigurations: this location is deprecated, use Build/Scripts/GetConfigurations instead" >&2
exec "$(dirname "${BASH_SOURCE[0]}")/../Build/Scripts/GetConfigurations" "$@"
