#!/bin/bash
echo "ScriptsLib/GetClangVersion: this location is deprecated, use Build/ScriptsLib/GetClangVersion instead" >&2
exec "$(dirname "${BASH_SOURCE[0]}")/../Build/ScriptsLib/GetClangVersion" "$@"
