#!/bin/bash
echo "ScriptsLib/GetDefaultShellVariable: this location is deprecated, use Build/Scripts/GetDefaultShellVariable instead" >&2
exec "$(dirname "${BASH_SOURCE[0]}")/../Build/Scripts/GetDefaultShellVariable" "$@"
