#!/bin/bash
echo "ScriptsLib/GetDefaultShellVariable: this location is deprecated, use Build/ScriptsLib/GetDefaultShellVariable instead" >&2
exec "$(dirname "${BASH_SOURCE[0]}")/../Build/ScriptsLib/GetDefaultShellVariable" "$@"
