#!/bin/bash
echo "ScriptsLib/GetMessageForMissingTool: this location is deprecated, use Build/ScriptsLib/GetMessageForMissingTool instead" >&2
exec "$(dirname "${BASH_SOURCE[0]}")/../Build/ScriptsLib/GetMessageForMissingTool" "$@"
