#!/bin/bash
echo "ScriptsLib/MakeDirectorySymbolicLink: this location is deprecated, use Build/Scripts/MakeDirectoryLink instead" >&2
exec "$(dirname "${BASH_SOURCE[0]}")/../Build/Scripts/MakeDirectoryLink" "$@"
