#!/bin/bash
echo "ScriptsLib/MakeSymbolicLink: this location is deprecated, use Build/Scripts/MakeSymbolicLink instead" >&2
exec "$(dirname "${BASH_SOURCE[0]}")/../Build/Scripts/MakeSymbolicLink" "$@"
