#!/bin/bash
echo "ScriptsLib/MakeDirectorySymbolicLink: this location is deprecated, use Build/ScriptsLib/MakeDirectorySymbolicLink instead" >&2
exec "$(dirname "${BASH_SOURCE[0]}")/../Build/ScriptsLib/MakeDirectorySymbolicLink" "$@"
