#!/usr/bin/env python3

#
# pkg-config-msvc - just like pkg-config --msvc-syntax but fixes up a few cases apparently not handled by pkg-config --msvc-syntax
#


import os
import sys
import subprocess

def isWindowsSystem_() -> bool:
    if os.name == 'nt':
        return True
    if sys.platform=='cygwin':
        return True
    return False

if __name__ == "__main__":
    args = sys.argv
    args = ["pkg-config"] + args[1:]
    useEnv = os.environ
    useCWD = None
    useLibDir = None
    if isWindowsSystem_():
        args = [args[0] , "--msvc-syntax"] + args[1:] 
        # useEnv['MSYS2_ENV_CONV_EXCL'] = '*'
        # useEnv['MSYS2_PATH_CONV_EXCL'] = '*'
        if useEnv['PKG_CONFIG_PATH']:
            # At least for msys, this must be unix format, cuz : treated as path separator
            # print(f"useEnv['PKG_CONFIG_PATH']={useEnv['PKG_CONFIG_PATH']}", file=sys.stderr)
            useEnv['PKG_CONFIG_PATH'] = subprocess.check_output(["cygpath", "-w", useEnv['PKG_CONFIG_PATH']]).decode().strip()
            # print (f"useEnv['PKG_CONFIG_PATH']={useEnv['PKG_CONFIG_PATH']}\n")
            useCWD = useEnv['PKG_CONFIG_PATH']
            # print (f"useCWD={useCWD}\n")
            # useCWD="C:\Sandbox\Stroika\DevRoot\Builds\Debug\lib\pkgconfig"
            useLibDir = subprocess.check_output(["cygpath","--mixed", useEnv['PKG_CONFIG_PATH']]).decode().strip() + "/"
            useEnv['PKG_CONFIG_PATH'] = "."
    try:
        # print(f"useEnv=${useEnv}\n")
        result = subprocess.run(args, capture_output=True, text=True, check=True, env=useEnv, cwd=useCWD)
        out = result.stdout.strip()
        out = out.replace ('/libpath:./', f'/libpath:"{useLibDir}"')
        print(out)
        if result.stderr:
            print(result.stderr, file=sys.stderr)
    except subprocess.CalledProcessError as e:
        print(f"{e.stdout}")
        print(f"{e.stderr}", file=sys.stderr)
        sys.exit (1)
    except FileNotFoundError:
        print(f"Error: Command '{command[0]}' not found.", file=sys.stderr) 
        sys.exit (1)
