#!/bin/bash
echo "ScriptsLib/pkg-config-msvc: this location is deprecated, use Build/ScriptsLib/pkg-config-msvc instead" >&2
exec "$(dirname "${BASH_SOURCE[0]}")/../Build/ScriptsLib/pkg-config-msvc" "$@"
