#!/bin/bash
echo "ScriptsLib/PrintProgressLine: this location is deprecated, use Build/Scripts/PrintProgressLine instead" >&2
exec "$(dirname "${BASH_SOURCE[0]}")/../Build/Scripts/PrintProgressLine" "$@"
