#!/bin/bash
echo "ScriptsLib/PrintLevelLeader: this location is deprecated, use Build/Scripts/PrintLevelLeader instead" >&2
exec "$(dirname "${BASH_SOURCE[0]}")/../Build/Scripts/PrintLevelLeader" "$@"
