#!/bin/bash
echo "ScriptsLib/PrintInfoAboutOSAndInstalledBuildTools: this location is deprecated, use Build/ScriptsLib/PrintInfoAboutOSAndInstalledBuildTools instead" >&2
exec "$(dirname "${BASH_SOURCE[0]}")/../Build/ScriptsLib/PrintInfoAboutOSAndInstalledBuildTools" "$@"
