#!/bin/bash
echo "ScriptsLib/PrintLevelLeader: this location is deprecated, use Build/ScriptsLib/PrintLevelLeader instead" >&2
exec "$(dirname "${BASH_SOURCE[0]}")/../Build/ScriptsLib/PrintLevelLeader" "$@"
