#!/bin/bash
echo "ScriptsLib/RunInDockerEnvironment: this location is deprecated, use Build/Scripts/RunInDockerEnvironment instead" >&2
exec "$(dirname "${BASH_SOURCE[0]}")/../Build/Scripts/RunInDockerEnvironment" "$@"
