#!/bin/bash
echo "ScriptsLib/RunLocalWSLRegressionTests: this location is deprecated, use Build/ScriptsLib/RunLocalWSLRegressionTests instead" >&2
exec "$(dirname "${BASH_SOURCE[0]}")/../Build/ScriptsLib/RunLocalWSLRegressionTests" "$@"
