#!/bin/bash
echo "ScriptsLib/RunLocalWSLRegressionTests: this location is deprecated, use Build/Scripts/RunLocalWSLRegressionTests instead" >&2
exec "$(dirname "${BASH_SOURCE[0]}")/../Build/Scripts/RunLocalWSLRegressionTests" "$@"
