#!/bin/bash

CONTAINER_NAME=DockerWindowsStroikaRegressionTester1
BRANCH=v2.1-Dev
VERSION=`ScriptsLib/ExtractVersionInformation STROIKA_VERSION FullVersionString`
# not sure why cygwin path setup with broken docker, but this works around it, for now... LGP 2020-02-25
DOCKER=docker.exe

[[ "$($DOCKER ps -a | grep $CONTAINER_NAME)" ]] && $DOCKER rm -f $CONTAINER_NAME

### FIX START THEN RUN EXEC so we can later re-attach withhotu changing CMD
echo "Running docker build (usually takes about 7hrs)"
$DOCKER run -id \
    --storage-opt "size=100GB" \
    -m 8G \
    --name $CONTAINER_NAME \
    sophistsolutionsinc/stroika-buildvm-windows-cygwin-vs2k19
$DOCKER exec \
    $CONTAINER_NAME \
    sh -c "git clone https://github.com/SophistSolutions/Stroika.git --branch $BRANCH"
$DOCKER exec \
    --workdir c:/Stroika \
    --env USE_TEST_BASENAME=Windows_VS2k19-In-Docker \
    $CONTAINER_NAME \
    sh -c "ScriptsLib/RegressionTests"
$DOCKER stop $CONTAINER_NAME
echo "Done with build, so copying out results"
$DOCKER cp $CONTAINER_NAME:Stroika/Tests/HistoricalRegressionTestResults/REGRESSION-TESTS-Windows_VS2k19-In-Docker-$VERSION-OUT.txt Tests/HistoricalRegressionTestResults/
$DOCKER cp $CONTAINER_NAME:Stroika/Tests/HistoricalPerformanceRegressionTestResults/PerformanceDump-Windows_VS2k19-In-Docker-$VERSION.txt Tests/HistoricalPerformanceRegressionTestResults/