#!/bin/bash

CONTAINER_NAME="${CONTAINER_NAME:-DockerWindowsStroikaRegressionTester1}"
BRANCH="${BRANCH:-v2.1-Dev}"
VERSION=`./ScriptsLib/ExtractVersionInformation STROIKA_VERSION FullVersionString`
# not sure why cygwin path setup with broken docker, but this works around it, for now... LGP 2020-02-25
DOCKER="${DOCKER:-docker.exe}"

[[ "$($DOCKER ps -a | grep $CONTAINER_NAME)" ]] && $DOCKER rm -f $CONTAINER_NAME

## Unclear why we need --interactive, but without it, the shell stops and we cannot exec anything -- LGP 2020-03-09
echo "Running docker build (usually takes about 4hrs)"
$DOCKER run \
    --detach \
    --interactive \
    --storage-opt "size=100GB" \
    --memory 8G \
    --cpus 4\
    --name $CONTAINER_NAME \
    sophistsolutionsinc/stroika-buildvm-windows-cygwin-vs2k19
$DOCKER exec \
    $CONTAINER_NAME \
    sh -c "git clone https://github.com/SophistSolutions/Stroika.git --branch $BRANCH"
$DOCKER exec \
    --workdir c:/Stroika \
    --env USE_TEST_BASENAME=Windows_VS2k19-In-Docker \
    $CONTAINER_NAME \
    sh -c "./ScriptsLib/RegressionTests"
$DOCKER stop $CONTAINER_NAME
echo "Done with build, so copying out results"
$DOCKER cp $CONTAINER_NAME:Stroika/Tests/HistoricalRegressionTestResults/REGRESSION-TESTS-Windows_VS2k19-In-Docker-$VERSION-OUT.txt Tests/HistoricalRegressionTestResults/
$DOCKER cp $CONTAINER_NAME:Stroika/Tests/HistoricalPerformanceRegressionTestResults/PerformanceDump-Windows_VS2k19-In-Docker-$VERSION.txt Tests/HistoricalPerformanceRegressionTestResults/
echo "Container $CONTAINER_NAME stopped but still around to examine/post-mortem"