#!/bin/bash

#
# Call from $StroikaRoot
#
#	Examples:
#		ScriptsLib/RunPerformanceRegressionTests
#		EXE=Builds/my-gcc-6.1.0-release-c++17/Tests/Test49 ScriptsLib/RunPerformanceRegressionTests
#		EXE=Builds/Release/Tests/Test49 USE_TEST_BASENAME=FRED ScriptsLib/RunPerformanceRegressionTests
#		MULTIPLIER=1 ScriptsLib/RunPerformanceRegressionTests
#
VER=`ScriptsLib/ExtractVersionInformation STROIKA_VERSION FullVersionString`

: "${USE_TEST_BASENAME:=UNKNOWN}"

MULTIPLIER=${MULTIPLIER-15}
if [ "$(uname -s)" == "Darwin" ] ; then
    EXE=${EXE-"Builds/Release/Tests/Test50"}
	if [ "$USE_TEST_BASENAME" == "UNKNOWN" ] ; then USE_TEST_BASENAME="MacOS-x86-XCode11"; fi
    CMDRUN_PREFIX="nice -10 "
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ] ; then
    # Do something under GNU/Linux platform
    EXE=${EXE-"Builds/g++-optimized/Tests/Test50"}
	if [ ! -e "$EXE" ] ; then EXE="Builds/Release/Tests/Test50"; fi
	if [ "$USE_TEST_BASENAME" == "UNKNOWN" ] ; then USE_TEST_BASENAME="linux-g++-7.3-x64"; fi
    CMDRUN_PREFIX="nice -10 taskset -c 0 "
elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ] ; then
    # Do something under Windows NT platform
    EXE=${EXE-"Builds/Release-U-32/Tests/Test50"}
	if [ "$USE_TEST_BASENAME" == "UNKNOWN" ] ; then USE_TEST_BASENAME="Windows-x86-vs2k17"; fi
    CMDRUN_PREFIX=""
elif [ "$(expr substr $(uname -s) 1 6)" == "CYGWIN" ] ; then
    # Do something under Windows NT platform
    EXE=${EXE-"Builds/Release-U-32/Tests/Test50"}
	if [ "$USE_TEST_BASENAME" == "UNKNOWN" ] ; then USE_TEST_BASENAME="Windows-x86-vs2k17"; fi
    CMDRUN_PREFIX=""
else
    echo "WARNING - unrecognized OS"
fi


echo -n "$CMDRUN_PREFIX" "$EXE --x $MULTIPLIER --show > Tests/HistoricalPerformanceRegressionTestResults/PerformanceDump-$USE_TEST_BASENAME-$VER.txt ... "
$CMDRUN_PREFIX $EXE --x $MULTIPLIER --show > Tests/HistoricalPerformanceRegressionTestResults/PerformanceDump-$USE_TEST_BASENAME-$VER.txt
echo "done"
