#!/bin/bash
echo "ScriptsLib/RunRemoteRegressionTests: this location is deprecated, use Build/Scripts/RunRemoteRegressionTests instead" >&2
exec "$(dirname "${BASH_SOURCE[0]}")/../Build/Scripts/RunRemoteRegressionTests" "$@"
