#!/bin/bash
echo "ScriptsLib/RunRemoteRegressionTests: this location is deprecated, use Build/ScriptsLib/RunRemoteRegressionTests instead" >&2
exec "$(dirname "${BASH_SOURCE[0]}")/../Build/ScriptsLib/RunRemoteRegressionTests" "$@"
