#!/bin/bash

StroikaRoot=$1


docker run \
	-u`id -u`:`id -g` -v /etc/passwd:/etc/passwd:ro -v /etc/group:/etc/group:ro \
	--security-opt seccomp=unconfined \
	-it\
	--name regression-tests \
	-h regression-tests \
	-d \
	-v $StroikaRoot:/Sandbox-StroikaRoot \
	-w /Sandbox-StroikaRoot \
	sophistsolutionsinc/stroika-buildvm-ubuntu1804-regression-tests \
	bash

#	sh -c "./ScriptsLib/RegressionTests.sh"

### NB: COLUMNS=/LINES= is poor workaround for lack of terminal size propagation from terminal to docker interactive session
echo "note - to connect to this container and view it's status, use:"
echo "   docker exec -it -e COLUMNS=\"`tput cols`\" -e LINES=\"`tput lines`\" regression-tests bash"
