#!/bin/bash
echo "ScriptsLib/SubstituteBackVariables: this location is deprecated, use Build/Scripts/SubstituteBackVariables instead" >&2
exec "$(dirname "${BASH_SOURCE[0]}")/../Build/Scripts/SubstituteBackVariables" "$@"
