#!/bin/bash

# From https://stackoverflow.com/questions/4023830/how-to-compare-two-strings-in-dot-separated-version-format-in-bash
#   Returns 0 if equal, 1 if >, and 2 if < (sb -1, for less, but cannot return that here cuz mapped to 255)
#
# EXAMPLES
#        ./ScriptsLib/VersionCompare 2.4 2.2 ; echo $? 
#        ./ScriptsLib/VersionCompare 2.4 2.4 ; echo $? 
#        ./ScriptsLib/VersionCompare 2.4 2.5 ; echo $? 
                
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    echo ret0
    return 0
}

vercomp $1 $2
exit $?