#!/bin/sh

echo "WORKAROUND https://devblogs.microsoft.com/cppblog/msvc-address-sanitizer-one-dll-for-all-runtime-configurations/"
echo "WORKAROUND https://developercommunity.visualstudio.com/t/ASAN-177-clang_rtasan_dynamic-x86_64d/10436682?viewtype=all"
echo "To run under debugger, and maybe for other reasons, handy to copy these DLLs to dirs where you have your executables"
echo "THIS IS A HORRIBLE HACK - but maybe handy for short term til MSFT fixes vs2k"
## NEEDED VS2k 17.7x, not before and unclear if needed after
for cfg in  `./ScriptsLib/GetConfigurations` 
do 
    # check if ASAN here and if windows before doing copy
    if [ -e Builds/$cfg ] 
    then
        echo "Copying ASAN dlls for $cfg"
       cp C\:/Program\ Files/Microsoft\ Visual\ Studio/2022/Community/VC/Tools/MSVC/*/bin/HostX64/x64/clang* Builds/$cfg/Tests 
       for trgDir in ./Builds/$cfg/Samples-*
       do
         cp C\:/Program\ Files/Microsoft\ Visual\ Studio/2022/Community/VC/Tools/MSVC/*/bin/HostX64/x64/clang* $trgDir
        done
   fi
done
