#!/bin/bash
echo "ScriptsLib/WarnIfNotWindowsDeveloperMode: this location is deprecated, use Build/ScriptsLib/WarnIfNotWindowsDeveloperMode instead" >&2
exec "$(dirname "${BASH_SOURCE[0]}")/../Build/ScriptsLib/WarnIfNotWindowsDeveloperMode" "$@"
