#!/bin/bash
echo "ScriptsLib/WarnIfNotWindowsDeveloperMode: this location is deprecated, use Build/Scripts/WarnIfNotWindowsDeveloperMode instead" >&2
exec "$(dirname "${BASH_SOURCE[0]}")/../Build/Scripts/WarnIfNotWindowsDeveloperMode" "$@"
