#!/bin/csh -f
# Copyright(c) Sophist Solutions Inc. 1990-1992.  All rights reserved
#
# $Header: /fuji/lewis/RCS/BuildMakeFileIndirect,v 1.5 1992/11/16 21:49:13 lewis Exp $
# 
# Description:
# 		BuildMakeFileIndirect <MakeFile> <MainTarget> <IndirectMakefile> [<CDTo>]
# 
#	eg:
#		BuildMakeFileIndirect Objects/Makefile ../Foundation.a  ../Makefile.unix
#   or
#		BuildMakeFileIndirect Makefile Foundation.a Makefile Objects
# 
# 
# Notes:
# 
# 
# Changes:
#		$Log: BuildMakeFileIndirect,v $
#		Revision 1.5  1992/11/16  21:49:13  lewis
#		.SILENT trick didn't work.
#
#		Revision 1.4  1992/11/16  20:06:37  lewis
#		Add .SILENT in output so we dont see warnings about using .DEFAULT rule.
#
#		Revision 1.3  1992/11/15  17:15:38  lewis
#		Hopefully fixed syntax errors.
#
#		Revision 1.2  1992/11/15  11:23:49  lewis
#		Totally new and MUCH better implemenation, due to help from kdj.
#
#
# 
#
#
#
if ( $#argv < 3 ) then
        echo "Usage: $0 <StroikaDir> <appendage> <MakefileAppendage> [<ConfigFileSuffix>]"
        exit 1
endif

set MakeFile=$1
set MainTarget=$2
set IndirectMakefile=$3
set CDTo=""

if ( $#argv >= 4 ) then
        set CDTo=$4
endif

rm -f $MakeFile
echo "# This Makefile was generated automatically with BuildMakeFileIndirect" > $MakeFile
echo "#" >> $MakeFile
echo "#" >> $MakeFile
echo "" >> $MakeFile
echo ".DEFAULT:" >> $MakeFile
echo "	@. Config; cd $CDTo; "'$'"(MAKE) -f ../Makefile.unix -"'$'"(MAKEFLAGS) "'$'"@" >> $MakeFile
echo "" >> $MakeFile
echo "all:" >> $MakeFile
echo "	@. Config; cd $CDTo; "'$'"(MAKE) -f ../Makefile.unix -"'$'"(MAKEFLAGS)" >> $MakeFile
echo "" >> $MakeFile



# For gnuemacs:
# Local Variables: ***
# mode:Text ***
# tab-width:4 ***
# End: ***
