#!/bin/csh -f
#
# Usage: checkForLocks <[dir]>
#
# Check recursively from the given directory if anything is locked.
# This should be much more elaborate, and should check for things
# that have RCS equivs, and are writable (IE ORPHANED), and also
# should have options to check if its locked by ME, or someone
# else, and should have options to see even if its locked by me,
# is it the one from this heirarchy (EG CHECK IF WRITEABLE)
#
# Lots to do to make this very usable...
#
#
set startDir = .;
if ("$#argv" == 1) then
	set startDir = $1;
endif

find $startDir -name RCS -exec _doRLOGs {} -L -R \;
