#!/bin/sh
#
# Copyright(c) Sophist Solutions Inc. 1990-1992.  All rights reserved
#
# $Header: /fuji/lewis/RCS/cmake,v 1.2 1992/06/28 01:47:49 lewis Exp $
#
#
# Description:
# 	Usage: cmake <Make-ARGS>
#
#	Run make with the given args, but prepend to makes arguments a bunch of configuration flags
# first gleamed from sourcing the configuration file "Config" expcected to be in the current directory
# (where the script is exectuted).
#
#
# TODO:
#
#
# Notes:
#
#
# Changes:
#	$Log: cmake,v $
#		Revision 1.2  1992/06/28  01:47:49  lewis
#		*** empty log message ***
#
#		Revision 1.2  1992/06/26  05:15:12  lewis
#		*** empty log message ***
#
#		Revision 1.1  1992/06/20  17:38:32  lewis
#		Initial revision
#
#		Revision 1.2  1992/04/09  15:22:32  lewis
#		Added header/description.
#
# 
#
#

. Config


# attempt at allowing you to filter cmake output to get rid of bugs
# warnings but dont know how to do pipes of stderr in bourne shell.
# in csh say |& but not sure about sh????
#
if [ "${CMAKE_FILTER:-0}" = 0 ]; then
	make CPlusPlusSystem=$CPlusPlusSystem CPlusPlus=$CPlusPlus CPPFlags="$CPPFlags" AR=$AR RANLIB=$RANLIB RM=$RM $*
else
	echo make CPlusPlusSystem=$CPlusPlusSystem CPlusPlus=$CPlusPlus CPPFlags="\"$CPPFlags\"" \
		AR=$AR RANLIB=$RANLIB RM=$RM $* '|&' $CMAKE_FILTER | csh -fst
fi

echo $FL


# For gnuemacs:
# Local Variables: ***
# mode:Text ***
# tab-width:4 ***
# End: ***
