#!/bin/csh -f
#
# Copyright(c) Sophist Solutions Inc. 1990-1992.  All rights reserved
#
# $Header: /fuji/lewis/RCS/MFL,v 1.1 1992/06/28 01:48:28 lewis Exp $
#
#
#
# Description:
#	Making makefiles links, object directories, and src crosslinks...
#
# 	Usage: MFL <DIR> <SUFFIX>
#
#
# TODO:
#
#
# Notes:
#
#
# Changes:
#	$Log: MFL,v $
#		Revision 1.1  1992/06/28  01:48:28  lewis
#		Initial revision
#
# Revision 1.1  1992/06/26  05:16:14  lewis
# Initial revision
#
#
# 
#
#
#
#


# Check usage...
if ( $#argv < 2 ) then
	echo "Usage: $0 <DIR> <SUFFIX>"
	exit 1
endif

set Dir=$1
set MakefileSuffix=$2

find $Dir -name Makefile$MakefileSuffix -exec _doMFL {} $MakefileSuffix \;



# For gnuemacs:
# Local Variables: ***
# mode:Text ***
# tab-width:4 ***
# End: ***
