#!/bin/csh -f
#
# Usage: patchMacText Dir
#
#

# Check usage...
if ( $#argv != 1 ) then
	echo "Usage: $0 Dir"
	exit 1
endif

set NewDir=$1

echo "toMacText'ing Makefile.mac's"
find $NewDir -name Makefile.mac -exec toMacText {} \;
toMacText $NewDir/Makefile.MoreProductions
