#!/bin/csh -f
#
# toMacText [file]*
#		will make the mac think that the given unix file is  a text file.
#		It does this by blowing away the apple-double % file, and replacing
#		it with one that just says text.
#
foreach i ($*)
	#cp /raptor/Stroika/Scripts.unix/prototype-text.% %$i
	set bn=`basename $i`
	set dn=`dirname $i`;
	cp /raptor/Stroika/Scripts.unix/prototype-text.% $dn/%$bn;
end;
