#!/bin/bash

docker build Ubuntu1804-Small/ -t sophistsolutionsinc/stroika-buildvm-ubuntu1804-small

docker build Ubuntu1804-RegressionTests/ -t sophistsolutionsinc/stroika-buildvm-ubuntu1804-regression-tests
