#!/bin/bash

docker build Ubuntu1804-Small/ -t sophist-solutions-inc/stroika-buildvm-ubuntu1804-small

docker build Ubuntu1804-RegressionTests/ -t sophist-solutions-inc/stroika-buildvm-ubuntu1804-regression-tests
