#!/bin/bash

docker run --security-opt seccomp=unconfined -d sophistsolutionsinc/stroika-buildvm-ubuntu1804-regression-tests --name regression-tests "cd Sandbox/Stroika-Dev && ./ScriptsLib/RegressionTests.sh"
