#!/bin/bash

docker run \
	--security-opt seccomp=unconfined \
	--name regression-tests \
	-d \
	sophistsolutionsinc/stroika-buildvm-ubuntu1804-regression-tests \
	sh -c "cd Sandbox/Stroika-Dev && git checkout V2.1-Dev && git pull && ./ScriptsLib/RegressionTests.sh"