#
#
#
name: build-Dev-Docker-Containers

on:
  workflow_dispatch:

jobs:
  build-Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build System Info
        shell: "bash"
        run: |
          df -h
          uname -a
          echo "DetectedHostOS: `./ScriptsLib/DetectedHostOS`"
      - name: Install Tools
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install dos2unix
      - name: Build Linux Container Images
        run: |
          DEBIAN_FRONTEND=noninteractive make --directory DockerBuildContainers --no-print-directory build-images
          DEBIAN_FRONTEND=noninteractive make --directory DockerBuildContainers --no-print-directory tag-images
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push Linux Container Images
        run: |
          DEBIAN_FRONTEND=noninteractive make --directory DockerBuildContainers --no-print-directory push-images

  build-Windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            make
      - uses: actions/checkout@v3
      - name: Build System Info
        shell: "bash"
        run: |
          df -h
          uname -a
          systeminfo
          echo "DetectedHostOS: `./ScriptsLib/DetectedHostOS`"
          echo NUMBER_OF_PROCESSORS=$NUMBER_OF_PROCESSORS
          echo "C:/ProgramData/Docker/config/daemon.json:" -n ; cat "C:/ProgramData/Docker/config/daemon.json"
      - name: Build Windows Container Images (STEP1-vs2k22)
        # Done as separate step since takes so long, and can see the time for this step more clearly... (could be omitted)
        #   DIDNT WORKmake --directory DockerBuildContainers --no-print-directory EXTRA_DOCKER_BUILD_ARGS="--storage-opt 'size=50GB'" sophistsolutionsinc/stroika-buildvm-windows-vs2k22
        run: |
          make --directory DockerBuildContainers --no-print-directory sophistsolutionsinc/stroika-buildvm-windows-vs2k22
      - name: Build Windows Container Images
        run: |
          make --directory DockerBuildContainers --no-print-directory build-images
      - name: Tag Windows Container Images
        run: |
          make --directory DockerBuildContainers --no-print-directory tag-images
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push Windows Container Images
        run: |
          make --directory DockerBuildContainers --no-print-directory push-images
