#
#
#
name: build-v3-Docker-Containers

on:
  workflow_dispatch:
    inputs:
      ignored:
        description: "ignored"
        required: false
        default: ""

jobs:
  build-Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build System Info
        shell: "bash"
        run: |
          df -h
          uname -a
          echo "DetectedHostOS: `./ScriptsLib/DetectedHostOS`"
      - name: Install Tools
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install dos2unix
      - name: Build Linux Container Images
        run: |
          DEBIAN_FRONTEND=noninteractive make --directory DockerBuildContainers --no-print-directory pull-base-images
          DEBIAN_FRONTEND=noninteractive make --directory DockerBuildContainers --no-print-directory build-images
          DEBIAN_FRONTEND=noninteractive make --directory DockerBuildContainers --no-print-directory tag-images
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push Linux Container Images
        run: |
          DEBIAN_FRONTEND=noninteractive make --directory DockerBuildContainers --no-print-directory push-images

  build-Windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            make
      - uses: actions/checkout@v3
      - name: Build System Info
        shell: "bash"
        run: |
          df -h
          uname -a
          systeminfo
          echo "DetectedHostOS: `./ScriptsLib/DetectedHostOS`"
          echo NUMBER_OF_PROCESSORS=$NUMBER_OF_PROCESSORS
      - name: Build Windows Container Images
        run: |
          make --directory DockerBuildContainers --no-print-directory pull-base-images
          make --directory DockerBuildContainers --no-print-directory build-images
          make --directory DockerBuildContainers --no-print-directory tag-images
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push Windows Container Images
        run: |
          make --directory DockerBuildContainers --no-print-directory push-images
