#
#
# NOT yet usable. NEED ability to PUSH to dockerhub - so some mechanism for private / secrets. Not
# investigated how todo yet. But still useful to test the build process working and a start towards remote
# build of containers
#
name: build-v3-Docker-Containers

on:
  workflow_dispatch:
    inputs:
      ignored:
        description: "ignored"
        required: false
        default: ""

jobs:
  build-Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build System Info
        shell: "bash"
        run: |
          echo "CWD: `pwd`"
          df -h
          uname -a
          echo "DetectOS: `./ScriptsLib/DetectHostOS`"
      - name: Build Linux Container Images
        run: |
          DEBIAN_FRONTEND=noninteractive make --directory DockerBuildContainers pull-base-images
          DEBIAN_FRONTEND=noninteractive make --directory DockerBuildContainers build-images
          DEBIAN_FRONTEND=noninteractive make --directory DockerBuildContainers tag-images
          # make --directory DockerBuildContainers push-images
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push Linux Container Images
        run: |
          DEBIAN_FRONTEND=noninteractive make --directory DockerBuildContainers push-images

  build-Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build System Info
        shell: "bash"
        run: |
          echo "CWD: `pwd`"
          df -h
          uname -a
          systeminfo
          echo "DetectOS: `./ScriptsLib/DetectHostOS`"
          echo NUMBER_OF_PROCESSORS=$NUMBER_OF_PROCESSORS
      - name: Build Windows Container Images
        run: |
          make --directory DockerBuildContainers pull-base-images
          make --directory DockerBuildContainers build-images
          make --directory DockerBuildContainers tag-images
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push Windows Container Images
        run: |
          make --directory DockerBuildContainers push-images
