name: C/C++ CI

on:
  push:
    branches: [ v2.1-Dev, v2.1-Release ]
  pull_request:
    branches: [  ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make run-tests
      run: make run-tests
