name: ubuntu-1804-run-tests

on:
  push:
    branches: [v2.1-Dev, v2.1-Release]
  pull_request:
    branches: []

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAKEFLAGS: "--jobs=3 QUICK_BUILD=1"
    container: sophistsolutionsinc/stroika-buildvm-ubuntu1804-regression-tests
    steps:
      - uses: actions/checkout@v2
      - name: configure Debug
        run: ./configure Debug --compiler-driver g++-8 --apply-default-debug-flags --trace2file enable --cppstd-version c++17
      - name: info
        run: |
          cat /Getting-Started-With-Stroika.md
          pwd
          cat ConfigurationFiles/Debug.xml
          g++ --version
          cat /proc/cpuinfo
      - name: make
        run: make tests
      - name: make run-tests
        run: make run-tests
