# PRELIM attempt at running a variety of tests on ubuntu 18.04 LTS

name: ubuntu-18.04-g++-8

on:
  push:
    branches: [v2.1-Dev, v2.1-Release]
  pull_request:
    branches: []

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      # vm appears to have 2 virtual CPUs, and QUICK_BUILD avoids some internal testing
      MAKEFLAGS: "--jobs=2 QUICK_BUILD=1"
    container: sophistsolutionsinc/stroika-buildvm-ubuntu1804-regression-tests
    steps:
      - uses: actions/checkout@v2
      - name: Build System Info
        run: |
          echo "CWD=" `pwd`
          cat /proc/cpuinfo
          df -h
      - name: Configure Debug
        run: |
          ./configure Debug --compiler-driver g++-8 --apply-default-debug-flags --trace2file enable --cppstd-version c++17
          cat ConfigurationFiles/Debug.xml
      # No need to explicitly call make third-party-components, libraries, but breaking out
      # as step allows the summary to show the time for each part.
      # Break out third-party-components to do clean so we dont run out of disk space
      - name: Make third-party-components
        run: |
          make third-party-components
          make clean
      - name: Make libraries
        run: make libraries
      - name: Make all
        run: make all
      - name: Run Tests
        run: make run-tests
      - name: Archive Results
        uses: actions/upload-artifact@v2
        with:
          name: Sample apps
          path: |
            Builds/Debug/Sample-*
            ./Builds/
