# PRELIM (but maybe never finsih) running tests using stright github actions with no docker

name: unix-native-run-tests

on:
  push:
    branches:
      - disabled

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: cat /proc/cpuinfo
      - name: configure Debug
        run: ./configure Debug --config-tag Unix --apply-default-debug-flags
      - name: make
        run: make tests
      - name: make run-tests
        run: make run-tests
