# PRELIM (but maybe never finsih) running tests using stright github actions with no docker

name: unix-native-run-tests

on:
  push:
    branches:
      - v2.1-Dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build System Info
        run: |
          echo "CWD=" `pwd`
          cat /proc/cpuinfo
          df -h
      - name: configure Debug
        run: ./configure Debug --config-tag Unix --apply-default-debug-flags
      - name: make
        run: make tests
      - name: make run-tests
        run: make run-tests
