# PRELIM (but maybe never finsih) running tests using stright github actions with no docker

name: wintest

on:
  push:
    branches:
      - v2.1-Dev

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build System Info
        run: |
          echo "CWD=" `pwd`
          df -h
      - name: xxx
        run: docker pull sophistsolutionsinc/stroika-buildvm-windows-cygwin-vs2k19
